name: ani-mm
channels:
  - conda-forge
dependencies:
  - python=3.10
  - openmm=8.0.0
  - openmm-torch  # for TorchForce (ANI in OpenMM)
  - ase
  - rdkit
  - pytorch  # conda-forge build (CPU or Metal acceleration on Apple Silicon)
  - pip
  - pip:
      - -e external/torchani
      - -e .[dev]

# Notes:
# 1. TorchANI is installed from the submodule (editable) instead of the outdated conda-forge package.
# 2. For CUDA-enabled Linux systems, you can instead install the official CUDA PyTorch wheels, then re-run: `pip install -e external/torchani`.
# 3. Ensure only one OpenMP runtime (avoid mixing system Homebrew llvm-openmp with conda-forge packages).
