name: ani-mm
channels:
  - conda-forge
dependencies:
  - python=3.10
  - openmm=8.0.0
  - ase
  - rdkit
  - pytorch  # conda-forge build (CPU or Metal acceleration on Apple Silicon)
  - torchani
  - openmm-torch  # for TorchForce (ANI in OpenMM)
  - pip
  - pip:
      - -e .[dev]

# Notes:
# 1. Keeping everything (OpenMM, PyTorch, TorchANI) from conda-forge reduces risk of multiple libomp runtimes. (NOTE: TorchANI from conda-forge is v2.1.0 as of 2024-06-10, newer versions may be available via GitHub source.)
# 2. For CUDA-enabled Linux systems, you can instead install the official CUDA PyTorch wheels and then add torchani via pip;
#    but ensure only one OpenMP runtime by avoiding mixing system Homebrew llvm-openmp with conda-forge packages.
# 3. If you previously installed torch via pip in this env, remove the env entirely before recreating to clear old libomp copies.
